while True:
    name,tmp,roll,chance,mi,ttp,mx = input().split()
    # name = input("Loot table:")
    # fr = input("from:")
    # roll = input("roll:")
    # chance = input("chance:")
    # mi = input("min:")
    # mx = input("max:")
    f = open("A.txt","a")
    f.write(f"private static final Identifier {name.upper()} = Identifier.ofVanilla(\"{"entities/"+name.lower()}\");\n")
    f.close()
    f = open("B.txt","a")
    f.write("LootTableEvents.MODIFY.register((key, tableBuilder, source) -> {\n")
    f.write(f"    if ({name.upper()}.equals(key.getValue())) "+"{\n")
    f.write("        LootPool.Builder poolBuilder = LootPool.builder()\n")
    f.write(f"                .rolls(ConstantLootNumberProvider.create({roll}))\n")
    f.write(f"                .conditionally(RandomChanceLootCondition.builder({1.0 if chance == 1 else chance}f))\n")
    f.write("                .with(ItemEntry.builder(codeitems.Skill_Point))\n")
    f.write(f"                .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create({mi}.0f, {mx}.0f)));\n")
    f.write("        tableBuilder.pool(poolBuilder);\n    }\n});\n")
    f.close()